CREATE TABLE HR.CHAT_MEMBER
(
  MEM_NUM    NUMBER,
  MEM_ID     VARCHAR2(10 BYTE)                  NOT NULL,
  MEM_PW     VARCHAR2(10 BYTE)                  NOT NULL,
  MEM_NAME   VARCHAR2(30 BYTE)                  NOT NULL,
  MEM_NICK   VARCHAR2(30 BYTE),
  MEM_EMAIL  VARCHAR2(40 BYTE),
  MEM_HP     VARCHAR2(20 BYTE),
  MEM_BIRTH  VARCHAR2(30 BYTE),
  REG_DATE   VARCHAR2(30 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX HR.CMEMBER_PK ON HR.CHAT_MEMBER
(MEM_NUM)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE HR.CHAT_MEMBER ADD (
  CONSTRAINT CMEMBER_PK
  PRIMARY KEY
  (MEM_NUM)
  USING INDEX HR.CMEMBER_PK
  ENABLE VALIDATE);